### ISSUE TITLE
Optimize github rate-limit quota usage of bot

### ISSUE THREAD

**Issue by bgrant0607** [kubernetes/contrib#1406] opened 2016-07-20 17:54 UTC
Forked from #1390

Github says we should be using webhooks instead of polling.

cc @lavalamp @kubernetes/contributor-experience

**Comment by bgrant0607** [comment] 2016-07-28 01:59
@rmmh @spxtr This is the issue I mentioned earlier today. Please explain what are you working on.

**Comment by rmmh** [comment] 2016-07-28 02:15
Right now each loop takes ~10 minutes to apply every munger to every open issue, so improving this will help responsiveness for everything. (Issue assignment, flake handling, etc)

The general idea is to change the core loop from `config.ForEachIssueDo(mungers.MungeIssue)` to `config.ForEachChangedIssueDo(mungers.MungeIssue)`. 

Changed issues could be determined by (from easiest to hardest swag estimate):
- searching for open issues and comparing their updated_at times to the last loop
- polling the [events api](https://developer.github.com/v3/activity/events/)
- having a webhook receive events and note issues that have been updated

This should reduce the number of API calls for each loop from O(number of open issues) to O(number of issues updated since last loop).

There may be some extra challenges with status updates (CLA, CI pass/fail information from Jenkins), since those don't appear to show up in the event-polling API. Maybe the issue updated_at field is enough to determine that?

**Comment by bgrant0607** [comment] 2016-07-28 02:39
Some info:

According to http://submit-queue.k8s.io/#/info, the bot is making 10 API calls per second.

Rate limit is 5k per hour, which is 1 per second:
https://developer.github.com/v3/#rate-limiting

So we use quota until we run out and then stall?

**Comment by rmmh** [comment] 2016-07-28 02:43
We cheat by using ETag headers, which doesn't consume our quota, but it
takes just as much time.

**Comment by eparis** [comment] 2016-07-28 07:15
github support suggested we use the `since` argument to https://developer.github.com/v3/issues/#list-issues-for-a-repository instead of checking every issue every time. That might be a couple of lines of code changed and be a big win.

web-sockets would get us a much better place, but last I looked, there wasn't a good library for web sockets and I didn't feel like writing it for go-github.

**Comment by apelisse** [comment] 2016-07-28 16:40
Yes, using `since` seems like the easy fix right now. It's not going to work for anything "time-based" like close-stale-pr though. Not something we can't work-around ...

**Comment by rmmh** [comment] 2016-07-28 17:25
Since also doesn't won't work for statuses, since they don't modify the updated_at timestamp. :(

We can categorize mungers based on whether they might have work whether or not updated_at has changed-- ones that look at statuses will always need to run.

Close-stale-pr could be run once a day-- when the munger first starts, and if 24 hours have elapsed since its last check.

**Comment by lavalamp** [comment] 2016-07-28 17:45
I think there is actually a decent go library for websockets? If that's the
only thing stopping us I'll try to find some time to go find it...

**Comment by rmmh** [comment] 2016-07-28 17:47
I think eparis meant webhooks (HTTP event pushes), not websockets.

**Comment by lavalamp** [comment] 2016-07-28 17:48
The github library we're using doesn't support that?

**Comment by rmmh** [comment] 2016-07-28 17:54
No, I don't think it has the appropriate types to unmarshal the JSON events that github POSTs to webhooks.

Changing the code to be push-based instead of pull based is significantly more work than just not running all the mungers on unchanged issues each loop.

**Comment by lavalamp** [comment] 2016-07-28 18:10
I'm not sure if it's really that bad. We'd switch to running the BeforeEach
functions periodically, we'd register for webhooks and dump the results in
a queue, then drain the queue for 10 minutes until it's time to run
BeforeEach again. My pkg/util/workqueue might be useful for this. We could
add some code to enforce that each issue/PR is munged only once per "loop".
I think we could make this change without modifying any of the mungers. It
would be a fair amount of work, I agree about that.

**Comment by spxtr** [comment] 2016-07-28 18:14
`go-github` has some support for webhooks, but it's not great. It gives you HMAC testing and most of the structs have the webhook fields, but you have to do all the listening and unmarshaling yourself. I do this [here](https://github.com/kubernetes/test-infra/blob/master/ciongke/cmd/hook/main.go)

**Comment by eparis** [comment] 2016-07-28 18:48
hooks. sockets. brain. vacation. off.

**Comment by foxish** [comment] 2016-08-05 07:52
From the bot statistics, it appears that `GetPR(...)` is the one API call that we're unable to cache well. Why is that? Is there something we could do in specific for it? 

![screenshot from 2016-08-05 00 39 55](https://cloud.githubusercontent.com/assets/906471/17430001/be76aba4-5aa6-11e6-8acb-1c302b5a7738.png)

**Comment by eparis** [comment] 2016-08-05 12:53
This was a message I got from github support long long ago talking about tokens.:

------------------------------------------------------------------

Also, I'm going to guess that you're using ETags for caching and If-None-Match for conditional requests, correct? If so, then I think you're seeing ETags change frequently for pull requests because of the way they're computed (taking nested resources into account). So, I'm wondering if you'd consider an alternative approach for fetching pull requests.

Before you re-fetch all pull requests, first fetch a list of pull requests which were updated since the last time you ran your process. The easiest way to do that is to use the Issues Search API (https://developer.github.com/v3/search/) which allows you to fetch open pull requests and specify the update date. The returned list will contain issue objects, not pull request objects, so you'd still need to fetch individual pull requests via the Pull Request API, but you'd have a list of pull requests which you really need to fetch. The updated_at for a pull requests should change only when the pull request updated. Can you give this a try and let me know if it helps or if you notice any unexpected behavior?

I also noticed that you make a lot of calls to fetch Git commits via the API (most of those result in a 304). Using a local Git clone and fetching data from that (e.g using a Git library like https://libgit2.github.com/) should be much faster and allow you to save some API calls as well.

**Comment by apelisse** [comment] 2016-08-05 14:35
By the way, regarding that last line. I've removed 98% of the calls to get
commit, removing 1400~ call per loop ...

**Comment by foxish** [comment] 2016-08-05 15:06
@apelisse That's awesome. I remembered seeing a different Get<> API call being on top of our stats earlier, and was wondering about it :). Maybe we could do the same for GetPR because it's performing so many uncached calls per loop. The approach @eparis suggested doesn't seem too hard to do. I can take a stab at it later today as well.

**Comment by apelisse** [comment] 2016-08-05 15:50
I think I have a better suggestion.

Today we do (if I read code correctly):
- For each loop
   - Fetch all open issues (within the specified range, but whatever in
this scenario)
   - Munge each issue (most of the time, will follow with:)
      - Fetch the PR (this is the problem)

We would improve significantly reduce the number of call by doing:
- For each loop
   - Fetch all open issues
   - Fetch all open pull-requests, associate the PR object with the issues
   - Munge each issue (PR is already there)

It would (without considering pagination) move from 1 call per PR to 1 call
for all the PRs.

And I think it can be implemented within a day

**Comment by foxish** [comment] 2016-08-05 16:10
That would definitely be a quicker fix, but there are 400+ open PRs on the main repository. Maybe we should run a quick test to see how many uncached API calls we use when we just run a single munger which fetches each PR exactly once. If the issue is that we are unable to cache PRs effectively between loops, that won't change if we keep fetching that many PRs in every loop. Right now, I saw that we made 419 calls to GetPR in the kubernetes submit-queue, of which only 3 were cache hits.

Interestingly, contrib sees 70 GetPR() calls (due to 70 PRs) and all of them are cache hits. I wonder if taking nested resources into account when checking if a PR has changed means that simply referencing a PR from elsewhere or some innocuous activity like that triggers a cache miss? I think it still doesn't explain the large number of misses I saw last night.

**Comment by eparis** [comment] 2016-08-05 16:43
this is a GREAT idea.  Since using the 'list all PRs' we can get 100 in one call...  So we'd turn the 400 PRs into 4 API calls.

The new flow would be:
get all issues and create all new MungeObjects
get all PRs and attach those to the MungeObjects
Run all mungers...

It'll boost memory consuption having to keep all issues and all PRs in ram instead of < page size at a time, but ram's cheap, right?

**Comment by apelisse** [comment] 2016-08-05 16:46
Cheaper than github tokens ;-)

**Comment by foxish** [comment] 2016-08-05 16:55
+1! @apelisse. We went over the data returned from the API for a list of PRs v/s a single one. There are minor differences, but the good news is that it shouldn't affect us, and it would be pretty a substantial saving in terms of the rate limit count. Definitely enough to deploy several more bots :)

**Comment by foxish** [comment] 2016-08-05 18:31
Just tried to whip up a quick version of the bot using 'list all PRs' instead of getPR(), and from what I see, it breaks the submit-queue (which is trying to get the attributes  `mergeable` and `merged`) and the size munger, because it relies on additions and deletions extracted from the PR data. Looks like we need to brainstorm further about how we could work around these.

The PR, in case anyone is interested is at https://github.com/kubernetes/contrib/pull/1490.

**Comment by apelisse** [comment] 2016-08-05 18:34
Size would be simplified by not looking at this value so it makes us a
favor...
We can check merge date for merged and we could look for the merge ref in
the repo to know if it's mergeable

**Comment by apelisse** [comment] 2016-10-01 19:57
I've set-up monitoring on the token so we can have a better idea of what's going on:
http://velodrome.kubernetes.io/dashboard/db/monitoring

**Comment by foxish** [comment] 2017-01-21 01:17
This issue was moved to kubernetes/test-infra#1625

**Closed by foxish** 2017-01-21 01:17 UTC
Labels: area/mungegithub, help wanted, kind/velocity-improvement
