### ISSUE TITLE
Merge bot is asking to run a test and those test doesn't start

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/contrib#536] opened 2016-03-03 13:02 UTC
I've seen this a bunch of times today - see e.g.:
https://github.com/kubernetes/kubernetes/pull/22264
https://github.com/kubernetes/kubernetes/pull/21851
https://github.com/kubernetes/kubernetes/pull/21904

And a bunch of others

@eparis @lavalamp @mwielgus @gmarek @fgrzadkowski

**Comment by eparis** [comment] 2016-03-03 13:55
@ixdy I know he was fighting try to get jenkins to pay attention yesterday...

**Comment by eparis** [comment] 2016-03-03 14:12
https://github.com/kubernetes/kubernetes/pull/21907

**Comment by eparis** [comment] 2016-03-03 14:14
https://github.com/kubernetes/kubernetes/pull/21982

**Comment by eparis** [comment] 2016-03-03 14:56
closing in favor of the issue in kubernetes/kubernetes, as that repo gets noticed...  The problem isn't in code in contrib, the problem is in Jenkins, so we don't have a great place to report it.

**Closed by eparis** 2016-03-03 14:56 UTC
Labels: bug

**Comment by wojtek-t** [comment] 2016-03-03 15:31
@eparis - ok thanks!
