### ISSUE TITLE
cluster-autoscaler, ingress, keepalived-vip: update vendored work-queue

### ISSUE THREAD

**Issue by foxish** [kubernetes/contrib#1623] opened 2016-08-25 16:43 UTC
The fix in https://github.com/kubernetes/kubernetes/pull/31396 needs to be updated:
- k8s.io/contrib/cluster-autoscaler/vendor/k8s.io/kubernetes/pkg/util/workqueue
- k8s.io/contrib/ingress/vendor/k8s.io/kubernetes/pkg/util/workqueue
- k8s.io/contrib/keepalived-vip/vendor/k8s.io/kubernetes/pkg/util/workqueue

cc @pwittrock @bprashanth @fgrzadkowski

**Comment by bprashanth** [comment] 2016-08-25 17:33
@aledbf fyi

**Comment by aledbf** [comment] 2016-08-25 17:38
@foxish @bprashanth what's the workflow for the `k8s.io/client-go` package? (it's empty now)
I just update 1498 but its [failing](https://travis-ci.org/kubernetes/contrib/builds/155114457)

**Comment by bprashanth** [comment] 2016-08-25 17:44
Hmm, does this work? https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go
@lavalamp

**Comment by lavalamp** [comment] 2016-08-25 17:52
The copy.sh script should work. We don't yet force you to run it.

**Comment by aledbf** [comment] 2016-08-25 18:00
> (it's empty now)

I'm sorry, I tried to say `https://github.com/kubernetes/client-go` it's empty.
The package `k8s.io/client-go` is being used only in `kubernetes/kubernetes` from the staging directory. The issue is when I try to update go dependencies using `godep save ./...`

**Comment by lavalamp** [comment] 2016-08-25 18:10
I don't understand what you're trying to do. Can you give explicit repro
steps? (I.e., what working directory are you in?)

**Comment by foxish** [comment] 2016-11-29 09:53
@fgrzadkowski Vendored deps in cluster-autoscaler don't seem to have been updated. PTAL.

**Comment by mwielgus** [comment] 2017-04-19 10:40
deps updated, closing.

**Closed by mwielgus** 2017-04-19 10:40 UTC
Labels: area/autoscaler, area/ingress, kind/bug
