### ISSUE TITLE
[ansible] Fix Cluster Addons for CentOS

### ISSUE THREAD

**Issue by danehans** [kubernetes/contrib#834] opened 2016-04-23 05:49 UTC
Cluster addons were fixed for coreos deployments with https://github.com/kubernetes/contrib/pull/672/files

However, the addons are not functioning for centos. Review https://github.com/kubernetes/contrib/pull/672/files and investigate why it only works on coreos, port the req'd functionality to centos

**Comment by rakesh-k** [comment] 2016-05-02 22:10
Having the same issue for redhat (should be similar to centos, I guess)

**Comment by ingvagabund** [comment] 2016-07-29 12:56
This should be fixed https://github.com/kubernetes/contrib/issues/886

**Comment by ingvagabund** [comment] 2016-08-24 15:34
Closing as duplicate of #886.

**Closed by ingvagabund** 2016-08-24 15:35 UTC
Labels: area/ansible
