### ISSUE TITLE
[ansible]Can't get latest kube from storage.googleapis.com

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/contrib#1618] opened 2016-08-25 06:00 UTC
When install latest kube using ansilbe, always failed with can't get file.
```
TASK [master : Download Kubernetes binaries] ***********************************
failed: [ec2-54-152-124-227.compute-1.amazonaws.com] (item=kube-apiserver) => {"dest": "/opt/kubernetes/1.4.0-alpha.2/kube-apiserver", "failed": true, "item": "kube-apiserver", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://storage.googleapis.com/kubernetes-release/release/v1.4.0-alpha.2/bin/linux/amd64/kube-apiserver"}
failed: [ec2-54-152-124-227.compute-1.amazonaws.com] (item=kube-controller-manager) => {"dest": "/opt/kubernetes/1.4.0-alpha.2/kube-controller-manager", "failed": true, "item": "kube-controller-manager", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://storage.googleapis.com/kubernetes-release/release/v1.4.0-alpha.2/bin/linux/amd64/kube-controller-manager"}
failed: [ec2-54-152-124-227.compute-1.amazonaws.com] (item=kube-scheduler) => {"dest": "/opt/kubernetes/1.4.0-alpha.2/kube-scheduler", "failed": true, "item": "kube-scheduler", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://storage.googleapis.com/kubernetes-release/release/v1.4.0-alpha.2/bin/linux/amd64/kube-scheduler"}
failed: [ec2-54-152-124-227.compute-1.amazonaws.com] (item=kubectl) => {"dest": "/opt/kubernetes/1.4.0-alpha.2/kubectl", "failed": true, "item": "kubectl", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://storage.googleapis.com/kubernetes-release/release/v1.4.0-alpha.2/bin/linux/amd64/kubectl"}
```
I check the latest version is v1.4.0-alpha.2, but there is no related files.
```
[root@ip-172-18-12-44 dma]# wget https://storage.googleapis.com/kubernetes-release/release/latest.txt
--2016-08-25 01:59:11--  https://storage.googleapis.com/kubernetes-release/release/latest.txt
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.217.112, 2607:f8b0:4004:80e::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.217.112|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15 [application/octet-stream]
Saving to: ‘latest.txt.1’

100%[===================================================================================================================================================================================================>] 15          --.-K/s   in 0s      

2016-08-25 01:59:12 (3.89 MB/s) - ‘latest.txt.1’ saved [15/15]

[root@ip-172-18-12-44 dma]# cat latest.txt
v1.4.0-alpha.2
[root@ip-172-18-12-44 dma]# wget https://storage.googleapis.com/kubernetes-release/release/v1.4.0-alpha.2/bin/linux/amd64/kube-apiserver
--2016-08-25 01:59:28--  https://storage.googleapis.com/kubernetes-release/release/v1.4.0-alpha.2/bin/linux/amd64/kube-apiserver
Resolving storage.googleapis.com (storage.googleapis.com)... 216.58.217.112, 2607:f8b0:4004:80e::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|216.58.217.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-25 01:59:28 ERROR 404: Not Found.
```

**Comment by mdshuai** [comment] 2016-08-25 06:01
@ingvagabund  thanks

**Comment by ingvagabund** [comment] 2016-08-25 08:01
Since there is no v1.4.0-alpha.2 release in https://github.com/kubernetes/kubernetes/tags. It is only a tag in the repository. What you can do is to build kubernetes from commit corresponding to the tag and use the distribution-rpm source type. Or extend the source types with ``custom-release`` or similar, where you provide your own path where the binaries can be downloaded.

**Comment by ingvagabund** [comment] 2016-08-25 12:01
Closing as this is not a bug.

**Closed by ingvagabund** 2016-08-25 12:01 UTC

**Comment by ingvagabund** [comment] 2016-08-25 12:04
@mdshuai or you can build kubernetes locally and set source type to localBuild

**Comment by mdshuai** [comment] 2016-08-26 01:43
@ingvagabund Today I can get v1.4.0-alpha.3 release. I don't why there is no v1.4.0-alpha.2. Anyway thanks for your help. When there is no latest release, I will use localBuild.
```
[root@dhcp-140-39 contrib]# wget https://storage.googleapis.com/kubernetes-release/release/v1.4.0-alpha.3/bin/linux/amd64/kube-apiserver
--2016-08-26 09:39:01--  https://storage.googleapis.com/kubernetes-release/release/v1.4.0-alpha.3/bin/linux/amd64/kube-apiserver
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.200.128, 2404:6800:4003:c00::80
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.200.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 150949424 (144M) [application/octet-stream]
Saving to: ‘kube-apiserver’

kube-apiserver                                              100%[========================================================================================================================================>] 143.96M  2.55MB/s    in 65s     

2016-08-26 09:40:12 (2.21 MB/s) - ‘kube-apiserver’ saved [150949424/150949424]

```

**Comment by mdshuai** [comment] 2016-08-26 01:50
latest/stable release version can be get from:
https://storage.googleapis.com/kubernetes-release/release/latest.txt
https://storage.googleapis.com/kubernetes-release/release/stable.txt
