### ISSUE TITLE
Switch munger to use GCS as a source of truth instead of Jenkins.

### ISSUE THREAD

**Issue by eparis** [kubernetes/contrib#602] opened 2016-03-22 17:19 UTC
```
I0322 17:13:04.205714       1 e2e.go:119] Got a non-success response 404 while reading data for kubernetes-e2e-gke/3126/finished.json
E0322 17:13:04.206332       1 submit-queue.go:242] GCS stable check returned different value than Jenkins.
```

**Comment by gmarek** [comment] 2016-03-22 18:49
Fascinating...

**Comment by gmarek** [comment] 2016-03-23 14:14
There's something clearly wrong there:
```
I0323 11:30:43.180208       1 e2e.go:119] Got a non-success response 404 while reading data for kubernetes-test-go/0/finished.json
```

If not for the fact that it happened few times today I'd say that it's some kind of race. Are we sure that we update 'last-build.txt' as a last thing when uploading results? It seems that the code https://github.com/kubernetes/contrib/blob/master/test-utils/utils/utils.go#L46 returned 0 for some reason. @ixdy @spxtr

**Comment by ixdy** [comment] 2016-03-23 19:40
Yeah, there is a race right now. Jenkins calls `hack/jenkins/upload-to-gcs.sh` which uploads the build logs and updates `latest-build.txt`, and then it calls `hack/jenkins/upload-finished.sh`, which uploads the `finished.json` file.

The eventual plan is to combine these two scripts, since there's no reason to have both of them, but the PR Jenkins jobs don't use `upload-finished.sh` yet. As an easier workaround we could probably switch the order they're called.

**Comment by ixdy** [comment] 2016-03-23 19:41
The build number of 0 is probably an artifact from Jenkins restarting.

**Comment by gmarek** [comment] 2016-03-23 20:37
@ixdy - can you take care of it?

**Comment by ixdy** [comment] 2016-03-23 23:56
Quick fix merged. Proper fix in process.

**Comment by gmarek** [comment] 2016-03-24 09:49
Thanks @ixdy - it seems to be working now.
@eparis, @spxtr - I'd like to switch to GCS as a main source of truth on Monday, if we won't see any differences until then. WDYT?

@justinsb - this should make it quicker for your PRs to go through, as we're testing GCS source to see if it's reliable enough.

cc @kubernetes/sig-testing

**Comment by justinsb** [comment] 2016-03-24 15:23
@gmarek that's great - I was looking at reintroducing my patches, but I think you've done a lot of the work in them for me!  I was going to start with the configuration-in-files PR (allowing more settings for each test runner), but it was sort of complicated by the fast that we are still using Jenkins.  So if we switch to GCS as the source of truth I should be able to redo my PRs much more easily!  (And there might not be a lot left in them!)

**Comment by ixdy** [comment] 2016-03-24 17:06
I'm always in favor of removing direct dependencies on Jenkins, FWIW. :)

**Comment by gmarek** [comment] 2016-03-25 13:37
There are more `0` latest_build_nubmers in last day. I wrote a small PR adding retries to the stability check: #631

**Comment by ixdy** [comment] 2016-03-25 17:37
Do you have data points on when you see the `0`s? it'd be good to see if it's correlated with the `latest_build.txt` file being updated.

**Comment by gmarek** [comment] 2016-03-25 18:03
It's in the munger logs. It runs on utility cluster.

**Comment by eparis** [comment] 2016-03-25 18:42
<wild non-intelligent speculation> Could it be that whatever it putting the file on the web server is calling open(O_CREAT); write(); close();  In which case an empty file could be served between the open() and the write() syncing to disk? Would that give this result? Is there a way to upload the files and then `mv` them into place to be served only after the data is present?

**Comment by ixdy** [comment] 2016-03-25 18:51
@eparis the file is uploaded with `gsutil`: https://github.com/kubernetes/kubernetes/blob/master/hack/jenkins/upload-to-gcs.sh#L51-L53, so I expect it to work correctly.

**Comment by eparis** [comment] 2016-03-25 19:31
I guess the way we would test if gsutil is using the potentially bad file creation pattern which might cause this would be to try using `gsutil cp $tmploc`; `gsutil mv $tmploc $finalloc`; istead of directly cp-ing to the final location...

**Comment by eparis** [comment] 2016-03-25 19:35
But this is a wild stab in the dark for a common C programming pattern that causes many issues and I'll believe you if you say that `gsutil cp` won't allow truncated/incomplete files to be retrieved. It's one of the big differences between `cp` and `install`.

**Comment by gmarek** [comment] 2016-03-29 12:29
It looks that adding retries was enough to make GCS-based checks stable. There still are 404 responses, but now they don't cause result differences. @eparis PTAL if you agree to switch Jenkins stable to GCS-stable now.

**Comment by gmarek** [comment] 2016-03-31 16:47
Ping @eparis

**Comment by eparis** [comment] 2016-03-31 16:56
I'm good with it if you are.

**Comment by gmarek** [comment] 2016-03-31 17:03
I just found one strange discrepancy
```
I0331 10:57:22.223462       1 mungegithub.go:59] Running mungers
I0331 10:57:23.405671       1 repo-updates.go:130] Loaded config from ./gitrepos/kubernetes:62eb7d3db8b0d968bd3346d067bb8f58e086352b
I0331 11:00:53.321208       1 github.go:865] PR 23387 setting "Submit Queue" Github status to "Github CI tests are not green."
I0331 11:01:49.532859       1 github.go:215] Made 2883 API calls since the last Reset 4.792867 calls/sec
I0331 11:01:49.532993       1 mungegithub.go:74] Sleeping for 5m32.690462038s
E0331 11:06:26.091455       1 submit-queue.go:243] GCS stable check returned different value than Jenkins.
I0331 11:06:56.862243       1 github.go:1263] Commenting "@k8s-bot test this [submit-queue is verifying that this PR is safe to merge]" in 23422
I0331 11:06:57.115367       1 github.go:865] PR 23422 setting "Submit Queue" Github status to "Requested and waiting for github e2e test to start running a second time."
I0331 11:07:22.223698       1 mungegithub.go:59] Running mungers
I0331 11:07:23.486026       1 repo-updates.go:130] Loaded config from ./gitrepos/kubernetes:62eb7d3db8b0d968bd3346d067bb8f58e086352b
I0331 11:07:27.496476       1 github.go:865] PR 23422 setting "Submit Queue" Github status to "Running github e2e tests a second time."
``` 

I'll add a bit more logging - it's an only one, so I guess it's a timing issue, but better safe than sorry.

**Comment by gmarek** [comment] 2016-03-31 19:52
cc @ixdy @fejta @spxtr @kubernetes/sig-testing - I believe that the failure above was just a timing issue. GCS-based stable will be responding slightly slower (Jenkins knows if test failed before we finish uploading stuff to GCS), but this should be OK.

If anyone has any objections against moving to GCS-based merge queue this is the time to speak up.

**Comment by gmarek** [comment] 2016-04-01 20:03
This issue changed its scope a bit. Renaming and reopening.

**Comment by gmarek** [comment] 2016-04-02 14:56
There's a number of errors:
```
I0402 14:02:44.144353       1 e2e.go:91] Jenkis based check for kubernetes-kubemark-5-gce build 802 returned false
E0402 14:02:44.322735       1 submit-queue.go:243] GCS stable check returned different value than Jenkins: false vs true.
```
which I need to investigate.

**Comment by gmarek** [comment] 2016-04-02 15:07
It didn't took long. The problem is retry logic and a small bug in GCSStable() logic (errors in checking statuses was treated as successes - fix #703), but the real culprit here is that in case of failed cluster startup, there's no 'finished.json'. We can probably live with the latter and treat 3 consecutive 404's as a failed test, but I'd rather be able to distinguish networking problems/jenkins issues (e.g. some random http errors/update problems), from real failures. Is it possible to create `finished.json` even if cluster isn't started? @ixdy

**Comment by ixdy** [comment] 2016-04-02 20:02
I'm pretty sure we intend to create a `finished.json` in all cases. Something may have gone wrong in that build, I'll investigate. @spxtr

**Comment by ixdy** [comment] 2016-04-02 20:12
Yeah, something was very broken:
```
+ JENKINS_BUILD_FINISHED=FAILURE
+ ./_tmp/upload-to-gcs.sh
Run finished at Sat Apr  2 06:35:26 PDT 2016
Uploading to gs://kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/802 (attempt 1)
Uploading build result: FAILURE
Traceback (most recent call last):
  File "/usr/local/bin/../share/google/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 12, in <module>
    import bootstrapping
ImportError: No module named bootstrapping
Uploading to gs://kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/802 (attempt 2)
Uploading build result: FAILURE
Traceback (most recent call last):
  File "/usr/local/bin/../share/google/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 12, in <module>
    import bootstrapping
ImportError: No module named bootstrapping
Uploading to gs://kubernetes-jenkins/logs/kubernetes-kubemark-5-gce/802 (attempt 3)
Uploading build result: FAILURE
Traceback (most recent call last):
  File "/usr/local/bin/../share/google/google-cloud-sdk/bin/bootstrapping/gsutil.py", line 12, in <module>
    import bootstrapping
ImportError: No module named bootstrapping
```

And the turnup failed for a similar reason:
```
ERROR: gcloud failed to load: No module named dateutil

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 executable:
    /usr/bin/python2

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.

If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/
ERROR: gcloud failed to load: No module named dateutil

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 executable:
    /usr/bin/python2

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.

If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/
```

This wasn't when the `gcloud update` was occurring, so I'm not sure what happened. The `gsutil` call to create `upload-started.json` worked fine.

**Comment by gmarek** [comment] 2016-04-04 16:32
I put the workaround in place, but it'll be go to get this fixed. @ixdy - do you have any estimate?

**Comment by ixdy** [comment] 2016-04-21 20:31
I'm not really sure what is left to be done on this issue. There's not much we can do when gcloud/gsutil gets completely hosed, as it did in https://github.com/kubernetes/contrib/issues/602#issuecomment-204793859.

**Closed** 2016-04-21 20:31 UTC
Labels: area/mungegithub
