### ISSUE TITLE
[ansible]kube-dns and logging CrashLoopBackOff after install

### ISSUE THREAD

**Issue by mdshuai** [kubernetes/contrib#1632] opened 2016-08-26 07:28 UTC
After install from github-release, dns and logging is CrashLoopBackOff
kube_version: 1.4.0-alpha.3
kube_source_type: github-release

```
[root@ip-172-18-0-91 ~]# kubectl get pod --namespace=kube-system
NAME                                                               READY     STATUS             RESTARTS   AGE
elasticsearch-logging-v1-3we4j                                     1/1       Running            0          30m
elasticsearch-logging-v1-eod2n                                     1/1       Running            0          30m
fluentd-elasticsearch-ec2-52-91-111-130.compute-1.amazonaws.com    1/1       Running            1          15m
fluentd-elasticsearch-ec2-54-197-207-211.compute-1.amazonaws.com   1/1       Running            0          15m
heapster-v1.0.2-2780992708-63e7w                                   4/4       Running            0          30m
kibana-logging-v1-0nryf                                            0/1       CrashLoopBackOff   5          30m
kube-dns-v11-0691y                                                 3/4       CrashLoopBackOff   7          30m
kubedash-mts5v                                                     1/1       Running            0          20m
kubernetes-dashboard-v1.1.0-3fh5w                                  1/1       Running            0          20m
monitoring-influxdb-grafana-v3-wv58o                               2/2       Running            0          30m

```

describe pod info: http://pastebin.test.redhat.com/406374
@ingvagabund

**Comment by ingvagabund** [comment] 2016-08-28 12:18
@sttts look familiar?

**Comment by sttts** [comment] 2016-08-29 07:51
Seeing the same in my docker-in-docker dev cluster: https://github.com/kubernetes/kubernetes/pull/27459

The health check fails. Even with `--v=9` kubedns does not output useful information.

**Comment by ingvagabund** [comment] 2016-08-29 10:57
Building the Kubernetes from the latest commit in Fedora's Koji and deploying with the ansible (master HEAD) on with F23 cluster in OpenStack:

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.3-169-g6fcbbe8", GitCommit:"6fcbbe86634f133171b3eafe860b1104620195e8", GitTreeState:"clean", BuildDate:"2016-08-29T09:59:09Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.3-169-g6fcbbe8", GitCommit:"6fcbbe86634f133171b3eafe860b1104620195e8", GitTreeState:"clean", BuildDate:"2016-08-29T09:59:09Z", GoVersion:"go1.7", Compiler:"gc", Platform:"linux/amd64"}
[root@jchaloup-fedora-kubernetes-master-6khvca-r2 ~]# kubectl nodes
Error: unknown command "nodes" for "kubectl"
Run 'kubectl --help' for usage.
$ kubectl get nodes
NAME           STATUS    AGE
10.8.170.212   Ready     14m
10.8.170.213   Ready     14m
$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080
Elasticsearch is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/kube-dns
Grafana is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana[root@jchaloup-fedora-kubernetes-master-6khvca-r2 ~]# 
InfluxDB is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY     STATUS    RESTARTS   AGE
kube-system   elasticsearch-logging-v1-3r42s         1/1       Running   0          18m
kube-system   elasticsearch-logging-v1-iwgvi         1/1       Running   0          18m
kube-system   fluentd-elasticsearch-10.8.170.212     1/1       Running   0          15m
kube-system   fluentd-elasticsearch-10.8.170.213     1/1       Running   0          15m
kube-system   heapster-v1.0.2-2125305049-qm2ej       4/4       Running   0          18m
kube-system   kibana-logging-v1-n6erc                1/1       Running   2          18m
kube-system   kube-dns-v11-istpx                     4/4       Running   0          18m
kube-system   monitoring-influxdb-grafana-v3-p9kcv   2/2       Running   0          18m
```

**Comment by ingvagabund** [comment] 2016-08-29 14:21
Finally deployed the ``1.4.0-alpha.3``. Noticed the kube-addons.sh script needs to be updated if running on secure port.

```sh
# kubectl --kubeconfig /etc/kubernetes/kubectl.kubeconfig cluster-info
Kubernetes master is running at https://kube-master-1:6443
Elasticsearch is running at https://kube-master-1:6443/api/v1/proxy/namespaces/kube-system/services/elasticsearch-logging
Heapster is running at https://kube-master-1:6443/api/v1/proxy/namespaces/kube-system/services/heapster
Kibana is running at https://kube-master-1:6443/api/v1/proxy/namespaces/kube-system/services/kibana-logging
KubeDNS is running at https://kube-master-1:6443/api/v1/proxy/namespaces/kube-system/services/kube-dns
Grafana is running at https://kube-master-1:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
InfluxDB is running at https://kube-master-1:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[root@kube-master-1 vagrant]# kubectl --kubeconfig /etc/kubernetes/kubectl.kubeconfig get pods --namespace kube-system
NAME                                   READY     STATUS    RESTARTS   AGE
elasticsearch-logging-v1-ob0z6         1/1       Running   0          8m
elasticsearch-logging-v1-r801d         1/1       Running   0          8m
fluentd-elasticsearch-kube-node-1      1/1       Running   0          1h
fluentd-elasticsearch-kube-node-2      1/1       Running   0          1h
heapster-v1.0.2-2125305049-oxj4c       4/4       Running   0          8m
kibana-logging-v1-lsl7m                1/1       Running   4          8m
kube-dns-v11-m7u91                     3/4       Running   1          8m
monitoring-influxdb-grafana-v3-xrx6h   2/2       Running   0          8m
[root@kube-master-1 vagrant]# kubectl --kubeconfig /etc/kubernetes/kubectl.kubeconfig version
Client Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.3", GitCommit:"b44b716965db2d54c8c7dfcdbcb1d54792ab8559", GitTreeState:"clean", BuildDate:"2016-08-25T18:39:33Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"4+", GitVersion:"v1.4.0-alpha.3", GitCommit:"b44b716965db2d54c8c7dfcdbcb1d54792ab8559", GitTreeState:"clean", BuildDate:"2016-08-25T18:31:09Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ingvagabund** [comment] 2016-08-29 14:23
Running with vagrant with fedora 23 on 6443 port.

**Comment by ingvagabund** [comment] 2016-08-30 08:40
> After install from github-release, dns and logging is CrashLoopBackOff

@mdshuai I have just hit the ``CrashLoopBackOff``. Though, all pods has got running eventually. It could be caused by million things. As long as it does not take much time to get all pods running, it is fine.

At the same time all the addons are outdated. They are copies of files from [1]. So with newer version of Kubernetes they do not have to be necessary friendly.

Do the ``kibana`` and ``kube-dns`` pods stay in ``CrashLoopBackOff`` forever?

[1] https://github.com/kubernetes/kubernetes/tree/master/cluster/addons

**Comment by sttts** [comment] 2016-08-30 08:41
My issue in https://github.com/kubernetes/contrib/issues/1632#issuecomment-243056080 was actually a kube-proxy problem. Adding `--masquerade-all` as a `kube-proxy` flag helped to restore service IP routing in containers.

**Comment by harobed** [comment] 2017-02-23 10:29
> Adding --masquerade-all as a kube-proxy flag helped to restore service IP routing in containers.

@sttts I don't understand, where I need to set that option ?

**Comment by harobed** [comment] 2017-02-23 11:35
I have add [here](https://github.com/kubernetes/contrib/blob/master/ansible/roles/node/templates/proxy.j2#L7):

```
KUBE_PROXY_ARGS="--masquerade-all --kubeconfig={{ kube_config_dir }}/proxy.kubeconfig"
```

I have redeployed with:

```
$ ansible-playbook ../playbooks/deploy-node.yml
```

`--masquerade-all` is enabled:

```
[root@kube-node-1 vagrant]# ps aux | grep "kube-proxy"
root      8996  1.1  2.4 518092 46704 ?        Ssl  11:15   0:12 /usr/bin/kube-proxy --logtostderr=true --v=0 --master=https://kube-master-1:443 --masquerade-all --kubeconfig=/etc/kubernetes/proxy.kubeconfig
```

But I have always `kubedns` error in log:

```
# kubectl -n kube-system logs -f kube-dns-v20-w5zfc kubedns
E0223 11:34:16.588433       1 reflector.go:214] pkg/dns/dns.go:154: Failed to list *api.Endpoints: Get https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
I0223 11:34:16.588599       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.254.0.1:443: getsockopt: connection refused. Sleeping 1s before retrying.
E0223 11:34:16.588965       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
I0223 11:34:17.590007       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.254.0.1:443: getsockopt: connection refused. Sleeping 1s before retrying.
E0223 11:34:17.590295       1 reflector.go:214] pkg/dns/dns.go:154: Failed to list *api.Endpoints: Get https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
E0223 11:34:17.590347       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
E0223 11:34:18.593910       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
E0223 11:34:18.593962       1 reflector.go:214] pkg/dns/dns.go:154: Failed to list *api.Endpoints: Get https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
I0223 11:34:18.593992       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.254.0.1:443: getsockopt: connection refused. Sleeping 1s before retrying.
I0223 11:34:19.594646       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.254.0.1:443: getsockopt: connection refused. Sleeping 1s before retrying.
E0223 11:34:19.594697       1 reflector.go:214] pkg/dns/dns.go:154: Failed to list *api.Endpoints: Get https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
E0223 11:34:19.594725       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
E0223 11:34:20.596361       1 reflector.go:214] pkg/dns/dns.go:154: Failed to list *api.Endpoints: Get https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
I0223 11:34:20.596405       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.254.0.1:443: getsockopt: connection refused. Sleeping 1s before retrying.
E0223 11:34:20.596437       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
I0223 11:34:21.597415       1 dns.go:172] Ignoring error while waiting for service default/kubernetes: Get https://10.254.0.1:443/api/v1/namespaces/default/services/kubernetes: dial tcp 10.254.0.1:443: getsockopt: connection refused. Sleeping 1s before retrying.
E0223 11:34:21.597469       1 reflector.go:214] pkg/dns/dns.go:154: Failed to list *api.Endpoints: Get https://10.254.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
E0223 11:34:21.597498       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://10.254.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.254.0.1:443: getsockopt: connection refused
```

**Comment by harobed** [comment] 2017-03-01 10:19
Fixed with last commits in master branch.

**Closed** 2018-02-19 17:14 UTC
Labels: lifecycle/rotten
