### ISSUE TITLE
Move Cluster-Autoscaler to a separate repo

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/contrib#2540] opened 2017-04-10 21:46 UTC
We would like to have a separate repo for cluster autoscaler to ensure proper branching and versioning.  

cc: @MaciekPytel @fgrzadkowski

**Comment by fgrzadkowski** [comment] 2017-04-11 08:40
Duplicate of https://github.com/kubernetes/contrib/issues/2533

**Closed by fgrzadkowski** 2017-04-11 08:40 UTC
Labels: area/autoscaler, area/autoscaling
