### ISSUE TITLE
TASK: [kubernetes-addons] fails for heapster-controller.yaml.j2

### ISSUE THREAD

**Issue by jojimt** [kubernetes/contrib#395] opened 2016-01-21 19:55 UTC
Seeing this error since the last hour or so:
TASK: [kubernetes-addons | MONITORING | Download monitoring files from Kubernetes repo] **\* 
ok: [k8master -> 127.0.0.1] => (item=grafana-service.yaml)
changed: [k8master -> 127.0.0.1] => (item=heapster-controller.yaml)
ok: [k8master -> 127.0.0.1] => (item=heapster-service.yaml)
ok: [k8master -> 127.0.0.1] => (item=influxdb-grafana-controller.yaml)
ok: [k8master -> 127.0.0.1] => (item=influxdb-service.yaml)

TASK: [kubernetes-addons | MONITORING | Convert pillar vars to ansible vars for monitoring files] **\* 
ok: [k8master -> 127.0.0.1] => (item=grafana-service.yaml)
changed: [k8master -> 127.0.0.1] => (item=heapster-controller.yaml)
ok: [k8master -> 127.0.0.1] => (item=heapster-service.yaml)
ok: [k8master -> 127.0.0.1] => (item=influxdb-grafana-controller.yaml)
ok: [k8master -> 127.0.0.1] => (item=influxdb-service.yaml)

TASK: [kubernetes-addons | MONITORING | Install template from converted saltfile] **\* 
ok: [k8master] => (item=grafana-service.yaml)
fatal: [k8master] => {'msg': "AnsibleError: file: /tmp/kubernetes/addons/cluster-monitoring/heapster-controller.yaml.j2, line number: 2, error: no test named 'None'", 'failed': True}
fatal: [k8master] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'group': 'root', 'uid': 0, 'changed': False, 'owner': 'root', 'item': 'grafana-service.yaml', 'state': 'file', 'gid': 0, 'secontext': 'system_u:object_r:etc_t:s0', 'mode': '0755', 'invocation': {'module_name': 'template', 'module_args': ''}, 'path': '/etc/kubernetes/addons/cluster-monitoring/grafana-service.yaml', 'size': 431}, {'msg': "AnsibleError: file: /tmp/kubernetes/addons/cluster-monitoring/heapster-controller.yaml.j2, line number: 2, error: no test named 'None'", 'failed': True}]}

FATAL: all hosts have already failed -- aborting

Any ideas/suggestions?

**Comment by jojimt** [comment] 2016-01-21 21:01
Update: Having ansible replace "is not None" with "is not none" in heapster-controller.yaml solves the problem. Probably, there is a better way to solve this.

**Comment by gbraxton** [comment] 2016-01-25 23:07
I am encountering this issue, but I don't see the string "is not None" anywhere in 'heapster-controller.yaml.j2'.

**Comment by jojimt** [comment] 2016-01-26 00:10
Are you hitting the same error? Or a different one? They might have changed the .yaml again.
You can work-around by creating a local copy of the .j2

**Comment by gbraxton** [comment] 2016-01-26 01:07
Recently ``` {% if pillar['num_nodes'] is defined and pillar['num_nodes'] is not None -%} ``` was changed to ```{% set num_nodes = pillar.get('num_nodes', -1) %}```. The regex in the task  "MONITORING | Convert pillar vars to ansible vars for monitoring files" needs to be updated to reflect.

**Comment by patrickeasters** [comment] 2016-01-26 13:48
For now, I just disabled cluster monitoring in the group_vars file since I don't need it quite yet in my lab environment.

I'll take a stab at a pull request this morning.

**Comment by patrickeasters** [comment] 2016-01-26 20:31
@gbraxton can you try again? My PR got merged in which worked great for me.

**Comment by gbraxton** [comment] 2016-01-26 21:37
It worked for me as well.

**Comment by danehans** [comment] 2016-02-12 20:55
I believe I ran into this issue. From my experience, the issue is that is not properly parsing the local grafana service file.  Here is my fix:

# git diff -w ansible/roles/kubernetes-addons/tasks/cluster-monitoring.yml
diff --git a/ansible/roles/kubernetes-addons/tasks/cluster-monitoring.yml b/ansible/roles/kubernetes-addons/tasks/cluster-monitoring.yml
index 4e0ac0f..1e4498e 100644
--- a/ansible/roles/kubernetes-addons/tasks/cluster-monitoring.yml
+++ b/ansible/roles/kubernetes-addons/tasks/cluster-monitoring.yml
@@ -24,8 +24,8 @@
 - name: MONITORING | Convert pillar vars to ansible vars for monitoring files
   local_action: replace
     dest="{{ local_temp_addon_dir }}/cluster-monitoring/{{ item }}.j2"
-    regexp="pillar\[\'(\w*)\'\]"
-    replace="\1"
+    regexp="pillar.get\(\'(\w*)\',\s-1\)"
+    replace={{ num_nodes }}
   sudo: no
   with_items:
     - grafana-service.yaml

**Closed** 2018-02-14 01:01 UTC
Labels: area/ansible, lifecycle/rotten
