### ISSUE TITLE
Merge bot is merging even when Critial builds are yellow

### ISSUE THREAD

**Issue by wojtek-t** [kubernetes/contrib#153] opened 2015-10-09 12:05 UTC
As an example:

PR https://github.com/kubernetes/kubernetes/pull/15014
was merged at 00:51 PST

at the same time "kubernetes-e2e-gce" was yellow

cc @lavalamp @eparis @brendandburns

**Comment by lavalamp** [comment] 2015-10-09 15:01
We think the problem is that it doesn't double-check before merging.

**Comment by eparis** [comment] 2015-10-09 16:10
Easy enough to fix, I guess the time between when it checks the google internal e2e and when it actually gets tested could be quite long...

**Comment by wojtek-t** [comment] 2015-10-09 17:05
Yup - I've checked and this is exactly this case.
And yes - it's usually ~30minutes.

**Comment by eparis** [comment] 2015-10-09 17:21
Fixed by #155

**Comment by roberthbailey** [comment] 2015-10-09 18:16
Fixed by #155

**Closed by roberthbailey** 2015-10-09 18:16 UTC
